### ISSUE TITLE
Evolve learn.gsf into our own learning platform

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/learn-platform#1]
* **PM:** Russ
* **Timescale:** 2024 Q1-2 
* **Tagline:** Build our own thriving community of Green Software Practitioners
* **Abstract:** The Linux Foundation currently host our Green Software Practitioner course. Learners who complete the course earn a ‘certificate of completion’ and digital badge. We would like to take full ownership of the course and quiz - hosting it ourselves.
* **GitHub:** Here for the time being

# Audience

Primarily software practitioners involved in the practice of building, deploying, or managing a software application. The course is also applicable to technology leaders, those looking to move into a career in green software and generally anyone interested in being part of the green software movement.

The course is aimed at those at the start of their green software journey; introducing fundamental concepts that are broadly applicable. The course could be seen as the first step on someone professional development.

According to data from [Evans Data Corporation](https://www.bairesdev.com/blog/how-many-software-developers-in-the-world/), there are nearly 27 million software developers worldwide. We would like to see ~3% certified in green software.

# ToC

* It will improve knowledge by helping software practitioners understand the concepts they need to know to build, maintain and run greener applications.
* It will change culture by creating a shared language and understanding of green software driving better conversations.

# Problem

* We have a disjointed training offering
  * We have our [own course website](https://learn.greensoftware.foundation/) which is currently the course materials
  * We also host the [course on the Linux Foundation](https://training.linuxfoundation.org/training/green-software-for-practitioners-lfc131/) where we have limited access and control
  * We are unable to award any certificates or badges through our website
  * There isn’t currently a clear strategy in terms of how these 2 solutions co-exist
* No course improvements since it was first launched in July 2022
  * With almost 50,000 completions we have a sizeable body of learner feedback that we are not acting on.
* The course content is not engaging enough
  * We have received feedback that “the content is not visual enough”, learners would like “more visuals and interactivities” and “more contextual information”
* We have limited means to distribute the course materials - Not all Member Organisations are able to access the public course due to their corporate network

# Solution

* A training strategy that brings together everything and everyone related to Principles
  * Covers the current course, certification, the GSF, the LF and wider eco-system
  * Links to a communication strategy
  * Start to position learn.gsf as a knowledge base bringing together all our resources
* Launch our own assessment platform
  * Host the GSP ‘final exam' on our own system so that learners enrol with us
  * Issue our own certificates and digital badges
  * Integrate into learn.gsf
* Redesign the https://learn.greensoftware.foundation/ website
  * Includes  both the GSP course and assessment
  * Keep the URLs most the same - No drop in SEO ranking
* Refresh the Green Software Practitioner course content to evolve the content format
  * Act on learner research and feedback
  * Videos, Visuals
  * Add a "Next steps" section to help continue a learners journey
* Move away from the Linux Foundation training platform
  * Amicable breakup
  * Redirect the existing LFC131 traffic (if possible)
  * Get the information of all existing learners (data dump)
* Obtain access to relevant tooling such that we can produce our eLearning content
  * Develop a plan for distributing the GSP content
  * As a [presentation](https://docs.google.com/presentation/d/14Ii4VINo2-cCbBYzn31F0zvyyEgM5y5MlVPrEihcf5A/edit)
  * As a SCORM package
  * To other learning platforms such as Coursea

## Minimum Viable Product

* Ability for a learner to take the GSP final exam on learn.gsf and receive a certificate & digital badge
* Refreshed learn.gsf website supporting both the GSP course content and assessment
* Refreshed course content based on existing feedback
* SCORM & PowerPoint versions of the course

# Resources

* Website Designer | Refreshed learn.gsf website | L |  
* Graphic Designer | Website graphicsCourse (info)graphics | S |  
* Instructional Designer | Refreshed GSP courseeLearning course | M |  
* eLearning video production | Videos | M | L
* eLearning authoring platform | eLearning course(SCORM) | M | S
* Assessment platform | Knowledge assessmentsCertificates | M | L
* Digital Badges platform | Digital badges |   | L
* Communication Lead | Comms strategySupport with user research

# OKRs

* Start building our own GSP community
  * KR1: X people have taken the Green Software Practitioner course on our platform 
  * KR2: Green Software Practitioner course hosted on X other training platforms (including member orgs)

# Milestones

- [ ] **Solution architecture finalised - January**
- [ ] **GSP v1.1 - February**
- [ ] **Assessment platform ready - March**
- [ ] **New website ready - March**
- [ ] **Pilot - March**
- [ ] **GSP v2.0 - March (TBC)**
- [ ] **Launch - April** 
- [ ] **Decommission LFC131 - April**

# References

[An expand project summary](https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/55312385/Evolve+learn.gsf+into+our+own+training+environment)
